# Configuration options for your blog - customise to taste
# This file contains no secret information, so can be stored in source control (unlike database.yml)
title: "Stefan Wienert's Blog"
url:   http://www.stefanwienert.net
author:
  name:    Stefan Wienert        # For copyright notice and ATOM feeds
  email:   info@stefanwienert.net # Exception emails will go here, and it is used in ATOM feeds
  open_id:                  # These are used to login to the admin area
      - http://wahldresdner.myopenid.com
      - http://secondaryopenid.com

